version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./src/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - ./src:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
